spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tester
    password: jumzip@d107
    url: jdbc:mysql://k8d107.p.ssafy.io:3306/testdb?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    dbcp:
      testOnBorrow: 'true'
      validationQuery: SELECT 1

# jwt
jwt:
  header: Authorization
  refresh-token: RefreshToken
  secret: #__________________
  access-token: AccessToken
  # 1 hour
  token-validity-in-seconds: 3600000
  # 1 day
  refresh-token-validity-in-seconds: 86400000
