server:
  port: 18081

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    #context-path: /

spring:
  profiles:
    active: dev

springdoc:
  version: '1.7.0'
  swagger-ui:
    disable-swagger-default-url: false
    use-root-path: true

  jpa:
    generate-ddl: 'true'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
